# Generated by Django 4.0.2 on 2022-03-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimDate', models.DateField()),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('RE', 'Rejected'), ('AC', 'Active'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('approvalDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField()),
                ('upcCode', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('dealership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectorName', models.CharField(max_length=30)),
                ('inspectionDate', models.DateField(blank=True, null=True)),
                ('dataEntryDate', models.DateField()),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='warranty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.warranty'),
        ),
    ]
